scheme: "Tempest"
author: "Protesilaos Stavrou (http://www.protesilaos.com)"
dbg: "282C36" # Dark background
dhl: "383C46" # Dark highlight
dt2: "686C76" # Dark bg text secondary
dt1: "A8ACB6" # Dark bg text primary
lbg: "F1F2F7" # Light background
lhl: "E1E2E7" # Light highlight
lt2: "818287" # Light bg text secondary
lt1: "414247" # Light bg text primary
red: "A97552" # Red
ora: "C78956" # Orange
gre: "48B7A7" # Green
blu: "3C8CBB" # Blue
mag: "C789A6" # Magenta
yel: "B9A552" # Yellow
cya: "55AFAF" # Cyan
vio: "7A7DCA" # Violet
