scheme: "Symbiosis"
author: "Protesilaos Stavrou (https://protesilaos.com)"
dbg: "111D1C" # Dark background
dhl: "212D2C" # Dark highlight
dt2: "616D6C" # Dark bg text secondary
dt1: "A1ADAC" # Dark bg text primary
lbg: "FCFAF9" # Light background
lhl: "ECEAE9" # Light highlight
lt2: "8C8A89" # Light bg text secondary
lt1: "4C4A49" # Light bg text primary
red: "B95846" # Red
ora: "A87226" # Orange
yel: "A89641" # Yellow
gre: "669824" # Green
cya: "48A597" # Cyan
blu: "3D8CAD" # Blue
vio: "9166AB" # Violet­­
mag: "BB7EAA" # Magenta
