scheme: "Bionis"
author: "Protesilaos Stavrou (http://www.protesilaos.com)"
dbg: "281D2A" # Dark background
dhl: "382D3A" # Dark highlight
dt2: "786D7A" # Dark bg text secondary
dt1: "A89DAA" # Dark bg text primary
lbg: "F9F5FA" # Light background
lhl: "E9E5EA" # Light highlight
lt2: "99959A" # Light bg text secondary
lt1: "39353A" # Light bg text primary
red: "C25A5B" # Red
ora: "CB6832" # Orange
yel: "BA8A00" # Yellow
gre: "4DA35C" # Green
cya: "439B9B" # Cyan
blu: "5A8ACD" # Blue
vio: "AA6BC5" # Violet
mag: "C25783" # Magenta
