scheme: "Oliveira"
author: "Protesilaos Stavrou (http://www.protesilaos.com)"
dbg: "252922" # Dark background
dhl: "353932" # Dark highlight
dt2: "757972" # Dark bg text secondary
dt1: "959992" # Dark bg text primary
lbg: "F1F3EB" # Light background
lhl: "E1E3DB" # Light highlight
lt2: "91938B" # Light bg text secondary
lt1: "51534B" # Light bg text primary
red: "A64E3C" # Red
ora: "A35C35" # Orange
gre: "5CA15A" # Green
blu: "1A8DAC" # Blue
mag: "A95F85" # Magenta
yel: "A59520" # Yellow
cya: "5CAA9A" # Cyan
vio: "7C85B7" # Violet
